"""add type column

Revision ID: 185b3b2d4bf5
Revises: 
Create Date: 2026-03-21 19:43:26.385210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185b3b2d4bf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_enrollment', sa.String(), server_default='Participante', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Enrollment', schema=None) as batch_op:
        batch_op.drop_column('type_enrollment')

    # ### end Alembic commands ###
